server:
  port: 8445
  servlet:
    context-path: /client    
  ssl:
    enabled: true
    key-store: classpath:localhost.jks
    key-store-type: JKS
    key-alias: localhost
    key-store-password: secret
    key-password: secret
    
client:  
  client-id: https://localhost:${server.port}/client
  login-callback-uri: https://localhost:${server.port}/client/logincb  
  authz-callback-uri: https://localhost:${server.port}/client/authzcb
  development-mode: true
  credential:
    resource: classpath:forhandsgranskning.jks
    alias: ec
    password: secret
    type: JKS
  signature-algorithm: ES256  
  authorization-server:
    id: https://localhost:8443/as
    authorization-endpoint: ${client.authorization-server.id}/oauth2/authorize
    token-endpoint: ${client.authorization-server.id}/oauth2/token
    user-info-endpoint: ${client.authorization-server.id}/userinfo
    authorization-server-key: classpath:as-key.crt  
  evidence-services:
  - name: "Evidence Service 1"
    id: https://evidence1.example.com
    required-scopes:
    - read
    api-endpoint: https://localhost:8446/evidence/service1
  - name: "Evidence Service 2"
    id: https://evidence2.example.com
    required-scopes:
    - read
    api-endpoint: https://localhost:8446/evidence/service2
  
logging:
  level:
    com:
      nimbusds:
        oauth2: DEBUG
    se:
      swedenconnect: DEBUG
      digg: DEBUG
    org:
      springframework:
        security: DEBUG
        

