server:
  port: 8445
  servlet:
    context-path: /client
  ssl:
    enabled: false
    
client:  
  client-id: https://localhost:${server.port}/client
  login-callback-uri: https://localhost:${server.port}/client/logincb  
  authz-callback-uri: https://localhost:${server.port}/client/authzcb
  development-mode: true
  credential:
    resource: classpath:keystore.jks
    alias: rsa
    password: secret
    type: JKS
  signature-algorithm: RS256
  authorization-server:
    id: https://localhost:8443
    authorization-endpoint: ${client.authorization-server.id}/oauth2/authorize
    token-endpoint: ${client.authorization-server.id}/oauth2/token
    user-info-endpoint: ${client.authorization-server.id}/userinfo
    authorization-server-key: classpath:as-key.crt  
  evidence-services:
  - name: "Evidence Service 1"
    id: https://evidence1.example.com
    required-scopes:
    - read
    api-endpoint: https://localhost:8446/evidence/service1
  - name: "Evidence Service 2"
    id: https://evidence2.example.com
    required-scopes:
    - read
    api-endpoint: https://localhost:8446/evidence/service2

openid:
  federation:
    issuer: http://preview-fed.test.digg.se
    subject: http://preview-fed.test.digg.se
    authority-hints:
      - https://federation.local.dev.digg.se/oidfed/sdg
    signing-jwks:
      - resource: classpath:sign-key.jks
        alias: rsa
        password: "secret"
        type: JKS
    federation-entity:
      contacts: federation@contact.se
      federation-fetch-endpoint: federation
      homepage-uri: homepage
      organization-name: orgName
    relying-party:
      scope: read openid
      grant-types:
        - authorization_code
        - refresh_token
      subject-type: pairwise
      token-endpoint-auth-method: private_key_jwt
      response-types:
        - code
      redirect-uris:
        - "https://preview.local.dev.digg.se/client/logincb"
        - "https://preview.local.dev.digg.se/client/authzcb"
      client-jwks:
        - classpath:certificate.pem
logging:
  level:
    com:
      nimbusds:
        oauth2: DEBUG
    se:
      swedenconnect: DEBUG
      digg: DEBUG
    org:
      springframework:
        security: DEBUG
        

